### Create
POST localhost:3000/api/devices
Content-Type: application/json

{ "name": "Device 5" }

### Read all
GET localhost:3000/api/devices

### Read
GET localhost:3000/api/devices/6447f42986d0a798429a2564

### Update
PUT localhost:3000/api/devices/6447f42986d0a798429a2564
Content-Type: application/json

{
  "uid": 234234,
  "vendor": "vendor",
  "status": true
}

### Delete
DELETE localhost:3000/api/devices/6447f42986d0a798429a2564
